---
galaxy_info:
  author: Chernyaev Y Alexey <a.u.chernyaev@gmail.com>
  description: Create new VM from Template
  min_ansible_version: 2.2
  #
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - system
dependencies: []
